### PR TITLE
Some changes to make it easier to work with

### PR DESCRIPTION
**Pull request by jessehouwing**
* Configurable root directory (default ensures backwards compat).
 * Multiline textbox for patterns under root directory.
 * Bumped version.
 * Improved debug output of variables.

---
This change is [Reviewable](https://reviewable.io/reviews/qetza/vsts-replacetokens-task/7)

### CODE REVIEW

**Comment by qetza** [comment]
Thanks for the enhancements @jessehouwing :smile:

**Comment by jessehouwing** [comment]
Consider your tool pretty useful ;).

**Comment by Banjo80** [comment]
Sollte jemand sagen das machst du sicher mit Absicht sage ich.......ja klar alles mit Absicht !

**Comment by qetza** [comment]
Release 1.2.0 including your PR is not published :)

**Pull request merged**
